// Package genhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package genhttp

import (
	"time"
)

// Comment defines model for Comment.
type Comment struct {
	AuthorName *string    `json:"author_name,omitempty"`
	Content    *string    `json:"content,omitempty"`
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Id         *int       `json:"id,omitempty"`
	PostId     *int       `json:"post_id,omitempty"`
}

// NewComment defines model for NewComment.
type NewComment struct {
	AuthorName string `json:"author_name"`
	Content    string `json:"content"`
}

// AddCommentJSONRequestBody defines body for AddComment for application/json ContentType.
type AddCommentJSONRequestBody = NewComment
