openapi: 3.0.0
info:
  title: Comment API
  version: 1.0.0
tags:
  - name: comment
    description: Operations related to comments on posts
paths:
  /posts/{id}/comments:
    post:
      tags:
        - comment
      summary: Add a comment to a blog post
      operationId: addComment
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewComment'
      responses:
        '201':
          description: Comment added
        '400':
          description: Bad request
        '404':
          description: Post not found
        '500':
          description: Internal server error
    get:
      tags:
        - comment
      summary: List all comments for a blog post
      operationId: listComments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    NewComment:
      type: object
      properties:
        author_name:
          type: string
        content:
          type: string
      required:
        - author_name
        - content
    Comment:
      type: object
      properties:
        id:
          type: integer
        post_id:
          type: integer
        author_name:
          type: string
        content:
          type: string
        created_at:
          type: string
          format: date-time
security:
  - BearerAuth: []
