openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
tags:
  - name: user
    description: Operations related to user management
paths:
  /user/register:
    post:
      tags:
        - user
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User created
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /user/login:
    post:
      tags:
        - user
      summary: Login a user
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
components:
  schemas:
    UserRegistration:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - name
        - email
        - password
    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    LoginResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
      type: object
      properties:
        token:
          type: string
      required:
        - token
    Error:
      allOf:
        - type: object
          required:
            - message
          properties:
            message:
              type: string
              example: "unexpected error"
        - $ref: '#/components/schemas/BaseResponse'
    BaseResponse:
      required:
        - serverTime
        - code
        - data
      type: object
      properties:
        serverTime:
          type: integer
          example: 1616048032
        data:
          type: object
        code:
          type: string
          example: "SUCCESS"