// Package genhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package genhttp

// AuthToken defines model for AuthToken.
type AuthToken struct {
	Token *string `json:"token,omitempty"`
}

// UserLogin defines model for UserLogin.
type UserLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// UserRegistration defines model for UserRegistration.
type UserRegistration struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = UserLogin

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = UserRegistration
