name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t fanzru/blog-app .
          docker push fanzru/blog-app

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_SSH_USER }}
          password: ${{ secrets.VM_SSH_PASSWORD }}
          port: 22
          script: |
            cd ~/blog-app || exit
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" > .env
            echo "DATABASE_DSN=${{ secrets.DATABASE_DSN }}" >> .env
            docker pull fanzru/blog-app:latest
            docker stop blog-app || true  # Stop the container if it exists
            docker rm blog-app || true    # Remove the container if it exists
            docker run -d -p 8080:8080 --name blog-app --env-file .env fanzru/blog-app:latest
